package com.keycome.twinkleschedule.util.const

const val KEY_SCHEDULE = "schedule"
const val KEY_SCHEDULE_ID = "schedule_id"
const val KEY_SCHEDULE_NAME = "schedule_name"
const val KEY_SCHEDULE_START_DATE = "schedule_start_date"
const val KEY_SCHEDULE_END_SECTION = "schedule_end_section"
const val KEY_SCHEDULE_END_DAY = "schedule_end_day"
const val KEY_SCHEDULE_END_WEEK = "schedule_end_week"

const val KEY_COURSE = "course"
const val KEY_COURSE_ID = "course_id"
const val KEY_COURSE_TITLE = "course_title"
const val KEY_COURSE_DAY = "course_day"
const val KEY_COURSE_SECTION = "course_section"
const val KEY_COURSE_WEEK = "course_week"
const val KEY_COURSE_TEACHER = "course_teacher"
const val KEY_COURSE_CLASSROOM = "course_classroom"

const val KEY_COURSE_COLOR = "course_color"
const val KEY_COURSE_TEXT_COLOR = "course_text_color"

const val KEY_ROUTINE = "routine"
const val KEY_ROUTINE_ID = "routine_id"
const val KEY_ROUTINE_MASTER_ID = "routine_master_id"
const val KEY_ROUTINE_NAME = "routine_name"
const val KEY_ROUTINE_START_DATE = "routine_start_date"
const val KEY_ROUTINE_SECTION_DURATION = "routine_section_duration"
const val KEY_ROUTINE_SECTION_INDEX = "routine_section_index"
const val KEY_ROUTINE_SECTION_START_TIME = "routine_section_start_time"
const val KEY_ROUTINE_SECTION_LIST = "routine_section_list"
const val KEY_ROUTINE_SECTION_SIZE = "routine_section_size"